NEWS
atticmatic/backends/shared.py
atticmatic/tests/unit/backends/test_shared.py

This bug is can be quite annoying because when you accidentally used
something like:
```ini
[location]
source_directories: backup_one  backup_two
;                              A (Additional space here)
```
It would call Attic/Borg with ('backup_one', '', 'backup_two') which in
turn backups your whole $PWD.

Use /\s+/ to split source_directories to handle 1+ spaces.

---

NEWS
README.md
atticmatic/backends/shared.py
atticmatic/tests/unit/backends/test_shared.py
sample/config

`source_directories_glob` can be used to enable glob support (defaults to
disabled). Let me know what needs to be changed (option names or other stuff) for this patch to get accepted.

Added support for file globs in source_directories.

---

borgmatic/borg/create.py
borgmatic/config/schema.yaml
borgmatic/tests/unit/borg/test_create.py
borgmatic/tests/unit/borg/test_prune.py

Related to #15 , https://tree.taiga.io/project/witten-borgmatic/issue/28
"Repository (or Archive) URLs, –prefix and –remote-path values support these placeholders" (https://borgbackup.readthedocs.io/en/stable/usage.html#borg-help-placeholders).
So, an even better way than adding a prefix or handling hostname and timestamp inside borgmatic is to use borg's placeholders which accomplishes the same thing as the old 
```
'{hostname}-{timestamp}'.format(...) 
```
This allows the usecase for both a prefix, label, removing timestamp and all of that, simply by changing storage.archive_name to something else, be it `MYPREFIX-{hostname}-{now}`, `{hostname}-MY_LABEL-{now}-{borgversion}` or whatever.
The default archive_name is now 
```
{hostname}-{now:%Y-%m-%dT%H:%M:%S.%f}
```
which is the same as …

Added storage.archive_name to config

---

AUTHORS
borgmatic/commands/borgmatic.py
borgmatic/commands/hook.py
borgmatic/config/generate.py
borgmatic/config/schema.yaml
borgmatic/config/validate.py
borgmatic/tests/unit/borg/test_hook.py

This PR adds support for user-defined shell scripts or single commands to be executed before and after a backup, or if an error has occurred. The intended use case is just as described in two existing issues [1, 2].  
Using the "before_backup", "after_backup", and "on_error" sections in the config file, it is possible to list one or multiple commands to execute. For example, this can be used to send emails after successful / failed backups, check disk space, execute mysqldump prior to creating a backup, etc.
For a better overview I've split the implementation into 3 commits:
1. af38fdea01a145a6c3437df0193823bb04d20e21 enables the value of the "example" fields in schema.yaml to be false by default, e.g. when used in conjunction with _type: bool_. 
This comes in handy to demonstrate the use …

Support for user hooks

---

README.md
borgmatic/borg/create.py
borgmatic/config/schema.yaml
borgmatic/tests/unit/borg/test_create.py

Using the `passcommand` option is safer than `passphrase` since it removes the need to store the encryption passphrase in the plain text config files.

Add `encryption_passcommand` configuration option

---

borgmatic/borg/create.py

Whilst trying to do a backup with both `--dry-run` and verbosity (either `-v 1` or `-v 2`) set, I encountered the following error:
borg create: error: argument -n/--dry-run: not allowed with argument -s/--stats
This pull request is a pretty quick and dirty fix.
Should probably also add some unit tests that have both verbosity and dry-run set.

Fix issue when using both --dry-run and -v options

---

AUTHORS
borgmatic/borg/check.py
borgmatic/commands/borgmatic.py
borgmatic/config/schema.yaml
borgmatic/config/validate.py
borgmatic/tests/unit/borg/test_check.py
borgmatic/tests/unit/config/test_validate.py
borgmatic/tests/unit/test_verbosity.py
borgmatic/verbosity.py

Borg supports checking a subset of archives in a repo by providing a prefix `--prefix PREFIX` when doing `check`. This PR adds functionality to use the same prefix defined in `retention` config to be passed as this param to borg.
http://borgbackup.readthedocs.io/en/stable/usage/check.html

Only check archives with matching prefix

---

sample/cron-alpine/borgmatic
sample/cron/borgmatic

This example is better suited for docker images based on alpine-linux. although just specifying the executable `borgmatic` is more general purpose i think. like this:
`0 3 * * * borgmatic 2>&1`
The output would show up in `docker logs` if you would run this an a container. Also in the syslog in any other scenario.

fixed error: /bin/ash: root: not found

---

borgmatic/borg/create.py
borgmatic/config/schema.yaml
borgmatic/tests/unit/borg/test_create.py

In response to a [discussion about libvirt and `--read-special` support](https://projects.torsion.org/witten/borgmatic/issues/80#issuecomment-817), I have modified borgmatic to support this feature.
One may wish to embellish the `read_special` YAML description with some more information if it's not detailed or specific enough.

Support read special parameter

---

borgmatic/commands/borgmatic.py

Borgmatic crashed on my machine because check_archives does not expect a parameter `json`.

check_archives does not take json parameter

---

README.md

Add a link to the software.opensuse.org page were both official and community packages of borgmatic are available to be downloaded or installed using 1-click-install.

Add link to  openSUSE packages

---

borgmatic/hooks/dump.py

Hallo witten,
I have found a little error in your *remove_database_dumps* function. If you have multiple dumps of a database type, the function parameter *dump_path* is overwritten in foreach loop with dump_file.
In the second loop, the database name is appended a second time to dump_path.
This pull request fixed the error in the cleanup routine for database dumps.
regards
Raphael

Fix error on cleanup multiple database dumps

---

borgmatic/borg/init.py

User-defined remote paths and verbosity settings are not being honoured in the first call to borg in borgmatic's init command. This call is used to check whether the repo already exists or not.
I've noticed this while creating a new repo and trying to use a remote-path set to force the use of a newer version of borg on a remote host instead of an old version, leading to scary error messages from an ancient version of borg during repo init.

Use --remote-path, --debug and --info when checking for repo existence

---

borgmatic/hooks/dump.py

Previously, only deleting a dump in a single-file format was supported.
This led to errors when performing a PostgreSQL directory format backup.

Support directory format dump cleanup.

---

borgmatic/hooks/postgresql.py
tests/end-to-end/test_database.py
tests/unit/hooks/test_postgresql.py

When the database name is set to 'all', borgmatic uses `pg_dumpall` instead of `pg_dump` to dump the database. `pg_dumpall` outputs a plain-text format and `pg_restore` does not accept that format. To run these plain-text outputs, `psql` is needed instead.
This pull request implements that. Thanks!

Fixed Broken pg_dumpall Restore

---

borgmatic/config/schema.yaml

Found a small mistake in the `after_everything` comment in the configuration file.

Doc config after_everything is "after" not before

---

tests/integration/test_execute.py

This allows test_execute not to depend on either vim or /dev/urandom.

tests/integration/test_execute: use plain Python rather than xxd

---

sample/systemd/borgmatic.timer

`OnCalendar=daily` will always run the timer at midnight. This is not ideal in some scenarios such as if it's being executed on a virtual server, as multiple virtual servers on the same host may all start hitting the disk at the same time, resulting in much worse disk performance compared to spreading them all out.
The 'traditional' way of avoiding this on Debian was using `/etc/cron.daily` for daily jobs. The cron package has a post-install script which adds `cron.daily`, `cron.weekly` and `cron.monthly` to `/etc/crontab`  with a random start time for each.
The more modern approach is using the `RandomizedDelaySec` systemd option. This will randomly stagger the start time of the timer. For example, `RandomizedDelaySec=1h` means that the timer can start anywhere between the `OnCalendar` …

Add randomized delay to systemd timer

---

borgmatic/config/schema.yaml
borgmatic/hooks/healthchecks.py
tests/unit/hooks/test_healthchecks.py

Hi :wave:, 
the following pull request adds the optional flag `verify_ssl` to the Healthchecks monitoring configuration. The variable defaults to `True`.
**Use case:** When running a self-hosted Healthchecks instance with self-signed certificates the ping command fails with the error:
```bash
/etc/borgmatic.d/config.yaml: Pinging Healthchecks finish
/etc/borgmatic.d/config.yaml: Healthchecks error: HTTPSConnectionPool(host='<local_network_dns_redacted>', port=443): Max retries exceeded with url: /ping/1bb6a6f7-679f-4b14-8f47-4480b542a28a (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
``` 
Let me know what you think. Hope you don't mind me creating the pull request here at …

feat: add verify_ssl flag for Healthchecks

---

borgmatic/config/schema.yaml
borgmatic/hooks/postgresql.py
tests/unit/hooks/test_postgresql.py

add `pg_dump_command`, `pg_restore_command` and `psql_command` configuration options. In this way, users can specify alternative commands on a per-database basis.
This is convenient if one needs to do backup/restore of different versions of postgres. A concrete example is the use of different versions of postgres running in docker containers for which one would want to use commands inside these containers while still being able to use pipes. Example:
```yaml
hooks:
postgresql_databases:
- name: my_pg_database
pg_dump_command: docker exec my_pg_database pg_dump
pg_restore_command: docker exec my_pg_database pg_restore
psql_command: docker exec my_pg_database psql
```
It partially fixes (#311) since it's just for the postgres hook.

specify pg dump/restore commands (#311)

---

borgmatic/config/schema.yaml
borgmatic/hooks/dispatch.py
borgmatic/hooks/dump.py
borgmatic/hooks/sqlite.py
docs/how-to/backup-your-databases.md
scripts/run-full-tests
tests/end-to-end/test_database.py
tests/unit/hooks/test_sqlite.py

fixes [#295](https://projects.torsion.org/borgmatic-collective/borgmatic/issues/295)
Will add to e2e tests once I understand how to do so.

feat: add dump-restore support for sqlite databases

---

borgmatic/borg/create.py
borgmatic/config/schema.yaml
tests/unit/borg/test_create.py

Resolves [#501](https://projects.torsion.org/borgmatic-collective/borgmatic/issues/501).
Will add tests once I know if this is correct.

feat: add optional check for existence of source directories

---

borgmatic/borg/export_tar.py
borgmatic/borg/extract.py
borgmatic/config/normalize.py
borgmatic/config/validate.py
tests/unit/config/test_normalize.py
tests/unit/config/test_validate.py

Yet to do (and write) some tests.

feat: file:// URLs support

---

borgmatic/commands/arguments.py

Was checking out [#462](https://projects.torsion.org/borgmatic-collective/borgmatic/issues/462), trying to find out where the default behaviour for `borgmatic` is documented.
Found this small spelling mistake.
This should change the [docs](https://torsion.org/borgmatic/docs/reference/command-line/) too right?

fix: docs cli reference create spelling

---

borgmatic/config/load.py
borgmatic/config/schema.yaml
tests/integration/config/test_load.py

Still have to add support for the third point from `generate.py::render_configuration()` and test it out.
Questions:
1. Should this support more complex cases like these:
```yaml
constants:
x: /home/divi/folder
y: {x}/file.txt
```

feat: allow defining custom variables in config file

---

borgmatic/config/load.py

Went with the more readable approach.

fix: replace primitive values in config without quotes

---

tests/integration/test_execute.py

This test is failing randomly with the following error:
```
E       flexmock.exceptions.MethodSignatureError: Arguments for call exit_code_indicates_error did not match expectations:
E         Received call:        exit_code_indicates_error(['sleep', '2'], None, "borg")
E         Expected call[1]:     exit_code_indicates_error(command=<Popen: returncode: None args: ['sleep', '2']>, exit_code=None, borg_local_path="borg")
E         Expected call[2]:     exit_code_indicates_error(command=['grep'], exit_code=2, borg_local_path="borg")
E         Expected call[3]:     exit_code_indicates_error(command=['grep'], exit_code=None, borg_local_path="borg")
```
The following line caused the mock to fail:
https://github.com/borgmatic-collective/borgmatic/blob/f256908b2709b643b4f7b27fd3fda150d3d32bca/bo …

Fix randomly failing test: test_log_outputs_kills_other_processes_when_one_errors

---

NEWS
borgmatic/borg/prune.py
borgmatic/commands/arguments.py
borgmatic/config/convert.py
borgmatic/config/schema.yaml
borgmatic/logger.py
docs/_includes/components/toc.css
docs/how-to/backup-to-a-removable-drive-or-an-intermittent-server.md
docs/how-to/develop-on-borgmatic.md
docs/how-to/inspect-your-backups.md
docs/how-to/set-up-backups.md
tests/integration/config/test_validate.py

Ran [typos](https://github.com/crate-ci/typos) on the source code to fix minor spelling mistakes.
(I Encountered some during development, so I thought maybe there were more).

Fix: run typos

---

docs/_includes/layouts/base.njk

I thought this was missing 😅.
A green/grey icon would be better for dark mode users, though.
Before:
After:
(Irrelevant, but why is the title on the home page not capitalised?)

add favicon to documentation

---

borgmatic/actions/bootstrap.py
borgmatic/actions/config/bootstrap.py
borgmatic/actions/create.py
borgmatic/borg/create.py
borgmatic/commands/arguments.py
borgmatic/commands/borgmatic.py
tests/integration/commands/test_arguments.py
tests/unit/actions/config/test_bootstrap.py
tests/unit/actions/test_create.py
tests/unit/borg/test_create.py
tests/unit/commands/test_arguments.py
tests/unit/commands/test_borgmatic.py

From [#697](https://projects.torsion.org/borgmatic-collective/borgmatic/issues/697)
> you need the output of borgmatic/config/collect.py:collect_config_filenames()
🤦 I thought this function will just return the filename and not the complete path (since we use the word "path" in and around these files too).
This should store the config used to create an archive inside the archive itself.
TODO:

feat: store configs used to create an archive in the archive and add borgmatic bootstrap

---

borgmatic/actions/restore.py
borgmatic/commands/arguments.py
borgmatic/config/schema.yaml
borgmatic/hooks/mongodb.py
borgmatic/hooks/mysql.py
borgmatic/hooks/postgresql.py
borgmatic/hooks/sqlite.py
tests/end-to-end/docker-compose.yaml
tests/end-to-end/test_database.py
tests/unit/actions/test_restore.py
tests/unit/hooks/test_mongodb.py
tests/unit/hooks/test_mysql.py
tests/unit/hooks/test_postgresql.py
tests/unit/hooks/test_sqlite.py

This PR adds a new feature that allows users to restore to a different port, host, or username. 
This Draft is to show the configuration version for PostgreSQL, I haven't tested this yet, just created to share progress.
Next Steps:

feat: allow restoring to different port/host/username

---

borgmatic/actions/create.py
borgmatic/borg/create.py
borgmatic/config/schema.yaml
tests/unit/actions/test_create.py
tests/unit/borg/test_create.py

[#725](https://projects.torsion.org/borgmatic-collective/borgmatic/issues/725)

feat: optionally disable config bootstrap

---

sample/systemd/borgmatic.service

First, ProtectSystem=strict will make the entire file system hierarchy (except /dev, /proc/ and /sys) read-only, so separate ReadOnlyPaths= is not necessary.
Second, ProtectHome=tmpfs will not just mount an empty tmpfs on /root, but also on /home and /run/user. As it's likely quite common to want to backup /home, this seems like a footgun.
Finally, it's quite likely that borgbackup will want access to root's SSH keys in order to connect to remote backup servers.
Note that all these options are commented out by default, so this is more of a documentation change than any real change in functionality.

Update systemd .service example

---

borgmatic/config/schema.yaml
borgmatic/hooks/mariadb.py
borgmatic/hooks/mysql.py
tests/unit/hooks/test_mariadb.py
tests/unit/hooks/test_mysql.py

Related Issue:
[https://projects.torsion.org/borgmatic-collective/borgmatic/issues/311](url)
Motivation and Context
Lets you run custom dump and restore commands for mysql to specify path for dump/restore binaries.
How Has This Been Tested?
Tested by me locally. I am able to run custom commands.
Types of change: New Feature
I have added tests to cover my changes.

Custom dump command for mysql

---

borgmatic/logger.py
tests/unit/test_logger.py

The `color` configuration directive is not taken into account and the output is shown as colored even when color is set to false in the configuration file.
This PR fixes the `color` configuration directive within the logger to read the actual value.
1. Set `color: false` in borgmatic configuration file
2. Run `borgmatic config validate`
```
~ $ borgmatic --version
1.8.13
~ $ cat $HOME/.config/borgmatic/config.yaml|grep color:
color: false
```

Fix color configuration directive

---

borgmatic/hooks/data_source/btrfs.py
tests/unit/hooks/data_source/test_btrfs.py

Problem:
`borgmatic` is trying to remove directory '' (empty string), if configured to use btrfs snapshots, and data from '/' subvolume is included in the backup.
It would look like this with '--verbosity 2':
```
backupserver: Calling bootstrap hook function remove_data_source_dumps
backupserver: Looking for bootstrap manifest files to remove in /tmp/borgmatic-*/borgmatic/bootstrap
backupserver: Calling btrfs hook function remove_data_source_dumps
backupserver: findmnt -t btrfs --json --list
backupserver: Looking for snapshots to remove in /var/log/.borgmatic-snapshot-*/var/log
backupserver: Looking for snapshots to remove in /var/cache/.borgmatic-snapshot-*/var/cache
backupserver: Looking for snapshots to remove in /swap/.borgmatic-snapshot-*/swap
backupserver: Looking for snapshots to …
```

Fix path handling error when handling btrfs '/' submodule

---

borgmatic/config/schema.yaml
borgmatic/hooks/monitoring/uptime_kuma.py
tests/unit/hooks/monitoring/test_uptimekuma.py

The option to skip tls verification allows the uptime kuma hook to work when the instance uses a self signed certificate in homelab or testing setups.

Add "verify_tls" option to Uptime Kuma hook.
